language: node_js
addons:
  ssh_known_hosts: "<deploy-host>"
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_985f5e5b0f2b_key -iv $encrypted_985f5e5b0f2b_iv
  -in deployment/deploy-key.enc -out /tmp/deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy-key
- ssh-add /tmp/deploy-key
jobs:
  include:
  - script: npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
